#include <stdio.h>

int main(int argc, char const *argv[])
{
    // DISEÑAR EL ALGORITMO NECESARIO PARA HABIÉNDOSE LEÍDO EL VALOR DE 2 VARIABLES NUM1 Y NUM2 SE INTERCAMBIEN LOS VALORES DE LAS VARIABLES, ES DECIR QUE EL VALOR QUE TENÍA NUM1 AHORA LO CONTENGA NUM2 Y VICEVERSA.

    return 0;
}
