#include <stdio.h>

int main(int argc, char const *argv[])
{
    /*
    DE LAS 20 PARTICIPANTES DE UN CONCURSO DE BELLEZA SE VAN REGISTRANDO DE UNO EN UNO LOS IGUIENTES DATOS:
        -APELLIDO Y NOMBRE
        -PUNTOS POR INTELIGENCIA
        -PUNTOS POR CULTURA GENERAL
        -PUNTOS POR BELLEZA
    SE NECESITA INFORMAR POR PANTALLA:
        - APELLIDO Y NOMBRE DE LA CONCURSANTE DE MAYOR PUNTAJE GENERAL.
        - PUNTAJE ACUMULADO POR TODAS LAS PARTICIPANTES EN CULTURA GENERAL, EN INTELIGENCIA Y EN BELLEZA.
        - DE LOS TRES PUNTAJES ACUMULADOS EN EL ÍTEM ANTERIOR CUAL FUE EL MENOR. 
    */

    return 0;
}
